### ISSUE TITLE
Request for the label data and evaluating code.

### ISSUE THREAD

**Issue by zw-SIMM** [zach-zhiling-zheng/ChatGPT_Chemistry_Assistant#2]
Amazing work! Very Impressive! Especially the prompt tutorials in SI, help a lot!
I have a request, can you provide the result of the paragraph and the corresponding extracted information, like in Figure 2?
More specifically, would you mind providing the ground truth data & chatgpt-predicted data, and metric code for evaluating the performance? I will appreciate very much! ​
Many many thanks for your well-done job!

**Comment by zach-zhiling-zheng** [comment]
Thank you for your note. We are pleased that you are interested in our work. In fact, the raw output has been further refined and is provided in the form of a "synthesis card" within [Synthesis_Embedding.zip]. This is intended for use in chatbots as factual data.

For the raw data output, if you could provide me with an email address, I can send you a summary file. This file contains labels for each individual synthesis parameter (filled green for True Positives, filled orange for False Positives, and filled grey for False Negatives). At the end of the document, we tally the numbers for each category and use simple Excel equations to calculate metrics like accuracy, F1 score, and so on. We currently have concerns regarding copyright issues, but **we are happy to provide this information upon request.**

Evaluating the output is not straightforward. Establishing a ground truth and automatically comparing it with the LLM output to generate metrics is challenging. It's important to note that evaluating LLM performance is not as simple as standard practices, which often involve merely comparing numerical values to calculate metrics. In this context, the complexity of text is the core issue, and it presents several challenges for the following reasons:

**Ambiguity in Language:** Language is inherently ambiguous, making it difficult to define a single "ground truth." For example, "N,N-Dimethylformamide anhydrous," "N,N-Dimethylformamide," "N,N dimethylformamide anhydrous," and "DMF" are all valid answers that mean the same thing. Meanwhile, "N,N-Dimethylformamide (DEF)," "DMFs," and "N,N dimethylformamide and ethanol" could be incorrect answers in certain cases. Enumerating all possible ground truths is challenging.

**Subjectivity:** Some synthesis parameters, such as modulators, involve subjective interpretation. The ground truth could vary depending on who is interpreting the data.

**Complexity and Nuance:** Some tasks require understanding complex relationships or arguments within the text. For instance, for the total solvent volume, the answers "12+2+0.5 ml," "12/0.5/2 mL," "14.5 mL," and "14 and 0.5 mL" may all be correct, depending on how the solvent class is selected.

**Scale:** As previously mentioned, LLMs can process vast amounts of text, making it impractical to manually label a sufficiently large dataset for evaluation.

**Adaptability:** LLMs are often fine-tuned for specific tasks or domains. A ground truth relevant for one application may not apply to another, complicating comprehensive evaluations. Also the temperature setting may do some changes to it.

As discussed in our paper, **all evaluations were performed by human annotators**.  Over 20,000 individual synthesis parameters, alongside their input paragraphs, were meticulously examined to categorize them as True Positives, True Negatives, or False Negatives based on definitions outlined in our paper. This process also allows us to determine whether the LLM is hallucinating facts or if the loss in accuracy is due to other factors, such as the writing style of the author, ambiguous descriptions, or errors in parsing the paper or converting PDFs to text.

**Comment by zw-SIMM** [comment]
Thank you so much for your sincere and detailed response and explanation. 
Here's my email address:  zhangwei2@simm.ac.cn
Much appreciate your willingness to provide this information!
Thanks for your write-up! 👍👍👍

**Comment by Dandelionym** [comment]
@zach-zhiling-zheng Hi, we are also interested in this excellent work, for the same request, we hope to communicate together further more regarding the Chemistry Assistant, may we have some discussion? 

Here's my email address: yingmingpu@gmail.com

Really appreciate your sharing. 🎉🎉🎉

**Comment by Katherine-xy** [comment]
@zach-zhiling-zheng Remarkable Work! Hi, we are currently working on a project that intersects with your work and we have same request for the raw data output and metric file. 
Here's my email address: shenxy189@gmail.com
Truly appreciate your sharing!

**Comment by DawnyWu** [comment]
@zach-zhiling-zheng  Hi, thank you for this excellent work and the detailed explanation of your evaluation process. We have the same request for the raw data output and the summary file to better understand the performance metrics.

Here's my email address:  1548331351@qq.com

Much appreciate your sharing! 🎉🎉🎉
